(define (domain lifts)
	(:requirements :strips)
	(:predicates 
        (move_one ?x ?y)
        (move_ten ?x ?y)
        (slow ?x ?y)
        (fast ?x ?y)
        (worker ?x ?y)
		(in ?x ?y)
	)
	(:action move_one_floor
		:parameters (?l ?from ?to)
		:precondition (and (slow ?l ?from) 
                   			(move_one ?from ?to))
		:effect  (and (slow ?l ?to)  
              		(not (slow ?l ?from)))
	)
	(:action move_ten_floor
		:parameters (?l ?from ?to)
		:precondition (and (fast ?l ?from) 
                   			(move_ten ?from ?to))
		:effect  (and (fast ?l ?to)  
              		(not (fast ?l ?from)))
	)
	(:action get_in_slow
		:parameters (?l ?w ?floor)
		:precondition (and (slow ?l ?floor) 
                   			(worker ?w ?floor))
		:effect  (and (in ?w ?l)  
              		(not (worker ?w ?floor)))
	)
	(:action get_in_fast
		:parameters (?l ?w ?floor)
		:precondition (and (fast ?l ?floor) 
                   			(worker ?w ?floor))
		:effect  (and (in ?w ?l)  
              		(not (worker ?w ?floor)))
	)
	(:action get_out_slow
		:parameters (?l ?w ?floor)
		:precondition (and (slow ?l ?floor) 
                   			(in ?w ?l))
		:effect  (and (worker ?w ?floor)  
              		(not (in ?w ?l)))
	)
	(:action get_out_fast
		:parameters (?l ?w ?floor)
		:precondition (and (fast ?l ?floor) 
                   			(in ?w ?l))
		:effect  (and (worker ?w ?floor)  
              		(not (in ?w ?l)))
	)
)
