/*************************************************************/
/* Automatically generated by './mkconfig.sh': do note edit! */
/*************************************************************/
#define LGL_OS "Linux 103ws21 3.10.0-957.1.3.el7.x86_64 x86_64"
#define LGL_COMPILED "Sat Oct 26 20:08:52 EEST 2019"
#define LGL_RELEASED "Fri Feb  7 22:21:52 CET 2014"
#define LGL_VERSION "ats1"
#define LGL_ID "ce8c04fc97ef07cf279c0c5dcbbc7c5d9904230a"
